### ISSUE TITLE
Error after updating to 3.0.0

### ISSUE THREAD

**Issue by Beebeeoii** [angular-material-extensions/select-country#47]
**Describe the bug**
Updated version to 3.0.0 and the component is causing some crashes to my dialog component.

**Error Log**
`core.js:4352 ERROR NullInjectorError: R3InjectorError(AppModule)[InjectionToken MatSelectCountryLangToken -> InjectionToken MatSelectCountryLangToken -> InjectionToken MatSelectCountryLangToken]: 
  NullInjectorError: No provider for InjectionToken MatSelectCountryLangToken!
    at NullInjector.get (http://localhost:4200/vendor.js:55616:27)
    at R3Injector.get (http://localhost:4200/vendor.js:65727:33)
    at R3Injector.get (http://localhost:4200/vendor.js:65727:33)
    at R3Injector.get (http://localhost:4200/vendor.js:65727:33)
    at NgModuleRef$1.get (http://localhost:4200/vendor.js:78848:33)
    at Object.get (http://localhost:4200/vendor.js:78552:35)
    at getOrCreateInjectable (http://localhost:4200/vendor.js:58682:39)
    at Module.ɵɵdirectiveInject (http://localhost:4200/vendor.js:69256:12)
    at NodeInjectorFactory.MatSelectCountryComponent_Factory [as factory] (http://localhost:4200/vendor.js:15135:189)
    at getNodeInjectable (http://localhost:4200/vendor.js:58787:44)
defaultErrorLogger @ core.js:4352
handleError @ core.js:4400
handleError @ core.js:8767
executeListenerWithErrorHandling @ core.js:15219
wrapListenerIn_markDirtyAndPreventDefault @ core.js:15251
(anonymous) @ platform-browser.js:582
invokeTask @ zone-evergreen.js:399
onInvokeTask @ core.js:27476
invokeTask @ zone-evergreen.js:398
runTask @ zone-evergreen.js:167
invokeTask @ zone-evergreen.js:480
invokeTask @ zone-evergreen.js:1621
globalZoneAwareCallback @ zone-evergreen.js:1647`

`core.js:4352 ERROR TypeError: Cannot read property 'focusInitialElementWhenReady' of undefined
    at MatDialogContainer._trapFocus (dialog.js:196)
    at MatDialogContainer._onAnimationDone (dialog.js:301)
    at MatDialogContainer_animation_dialogContainer_done_HostBindingHandler (dialog.js:328)
    at executeListenerWithErrorHandling (core.js:15216)
    at wrapListenerIn_markDirtyAndPreventDefault (core.js:15251)
    at animations.js:188
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Object.onInvoke (core.js:27488)
    at ZoneDelegate.invoke (zone-evergreen.js:363)
    at Zone.run (zone-evergreen.js:123)`

**Comment by KingDarBoja** [comment]
Hello @Beebeeoii 

Did you set `MatSelectCountryModule.forRoot('en')` on your root module (`app.module.ts` in this case)?

**Comment by Beebeeoii** [comment]
Hey @KingDarBoja 

Thank you for pointing out! Slipped that part.

**Comment by AnthonyNahas** [comment]
@KingDarBoja thank you
