### ISSUE TITLE
[Bug] Schematic not working for 2.0.0

### ISSUE THREAD

**Issue by KingDarBoja** [angular-material-extensions/select-country#33]
**Describe the bug**
The current schematic doesn't work with latest version (2.0.0).

**To Reproduce**
1. Setup Angular material by running `ng add @angular/material`
2. Now setup this library using the schematics by running `ng add @angular-material-extensions/select-country`
3. See error log below

```console
$ ng add @angular-material-extensions/select-country
Invalid peer dependency @angular/common found in package.
Invalid peer dependency @angular/core found in package.
Invalid peer dependency @angular/forms found in package.
Invalid peer dependency @angular/platform-browser found in package.
Invalid peer dependency @angular/common found in package.
Invalid peer dependency @angular/core found in package.
Invalid peer dependency @angular/forms found in package.
Invalid peer dependency @angular/platform-browser found in package.
Unable to find compatible package.  Using 'latest'.
Package has unmet peer dependencies. Adding the package may not succeed.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
An unhandled exception occurred: Cannot find module '@schematics/angular/utility/project'
Require stack:
- D:\Programming\angular_projects\kingdarboja-io\node_modules\@angular-material-extensions\select-country\schematics\helpers\angular\project.js
- D:\Programming\angular_projects\kingdarboja-io\node_modules\@angular-material-extensions\select-country\schematics\helpers\angular\index.js
- D:\Programming\angular_projects\kingdarboja-io\node_modules\@angular-material-extensions\select-country\schematics\helpers\index.js
- D:\Programming\angular_projects\kingdarboja-io\node_modules\@angular-material-extensions\select-country\schematics\ng-add\index.js
- D:\Programming\angular_projects\kingdarboja-io\node_modules\@angular-devkit\schematics\tools\export-ref.js
- D:\Programming\angular_projects\kingdarboja-io\node_modules\@angular-devkit\schematics\tools\index.js
- D:\Programming\angular_projects\kingdarboja-io\node_modules\@angular\cli\utilities\json-schema.js
- D:\Programming\angular_projects\kingdarboja-io\node_modules\@angular\cli\models\command-runner.js
- D:\Programming\angular_projects\kingdarboja-io\node_modules\@angular\cli\lib\cli\index.js
- D:\nvm\v12.14.0\node_modules\@angular\cli\lib\init.js
- D:\nvm\v12.14.0\node_modules\@angular\cli\bin\ng
See "C:\Users\INTEL\AppData\Local\Temp\ng-2ONrqt\angular-errors.log" for further details.
```

**Expected behavior**
No issues after running the schematic

**Desktop (please complete the following information):**
```
Version: 1.48.2 (user setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

<details><summary><b>Package.json</b></summary>

```json
{
  "name": "kingdarboja-io",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "prestart": "ngtw build",
    "start": "ng serve & ngtw watch",
    "build": "ngtw build --purge && ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "scully": "scully",
    "scully:build": "npm run build && scully",
    "scully:serve": "scully serve"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~10.0.10",
    "@angular/cdk": "^10.1.3",
    "@angular/common": "~10.0.10",
    "@angular/compiler": "~10.0.10",
    "@angular/core": "~10.0.10",
    "@angular/forms": "~10.0.10",
    "@angular/material": "^10.1.3",
    "@angular/platform-browser": "~10.0.10",
    "@angular/platform-browser-dynamic": "~10.0.10",
    "@angular/router": "~10.0.10",
    "@scullyio/init": "1.0.0-beta.0",
    "@scullyio/ng-lib": "latest",
    "@scullyio/scully": "latest",
    "prismjs": "^1.21.0",
    "rxjs": "~6.6.2",
    "tslib": "^2.0.1",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.6",
    "@angular/cli": "~10.0.6",
    "@angular/compiler-cli": "~10.0.10",
    "@types/jasmine": "~3.5.12",
    "@types/jasminewd2": "~2.0.8",
    "@types/node": "^14.6.0",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.2",
    "karma": "~5.1.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.3",
    "karma-jasmine": "~4.0.1",
    "karma-jasmine-html-reporter": "^1.5.4",
    "ng-tailwindcss": "^2.3.1",
    "protractor": "~7.0.0",
    "tailwindcss": "^1.6.2",
    "ts-node": "~8.10.2",
    "tslint": "~6.1.3",
    "typescript": "~3.9.7"
  }
}
```

</details>

**Comment by AnthonyNahas** [comment]
@KingDarBoja I would really appreciate a PR from you

**Comment by KingDarBoja** [comment]
Been working on providing some tests for the schematic to keep an eye on the issues while running it but right now getting a different issue due to the Injection Token on my test.

**Comment by AnthonyNahas** [comment]
Solution:

`npm i -s -D @schematics/angular@9.1.12`

this will solve the issue

**Comment by KingDarBoja** [comment]
Still gonna submit a PR with a schematic test file just in case. 😉

**Comment by AnthonyNahas** [comment]
awesome ;)
